### ISSUE TITLE
KeyError: 'inverted' while building

### ISSUE THREAD

**Issue by apeeters** [OttoWinter/esphomeyaml#12]
I am getting this stacktrace while compiling the code below using the Docker container:

```Traceback (most recent call last):
  File "/usr/local/bin/esphomeyaml", line 11, in <module>
    load_entry_point('esphomeyaml', 'console_scripts', 'esphomeyaml')()
  File "/usr/src/app/esphomeyaml/__main__.py", line 287, in main
    exit_code = write_cpp(config)
  File "/usr/src/app/esphomeyaml/__main__.py", line 125, in write_cpp
    get_variable(None)
  File "/usr/src/app/esphomeyaml/helpers.py", line 325, in get_variable
    func(config)
  File "/usr/src/app/esphomeyaml/components/binary_sensor/gpio.py", line 16, in to_code
    rhs = App.make_gpio_binary_sensor(config[CONF_NAME], exp_gpio_input_pin(config[CONF_PIN]))
  File "/usr/src/app/esphomeyaml/helpers.py", line 428, in exp_gpio_input_pin
    return exp_gpio_pin_(GPIOInputPin, conf, u'INPUT')
  File "/usr/src/app/esphomeyaml/helpers.py", line 407, in exp_gpio_pin_
    conf[CONF_INVERTED])
KeyError: 'inverted'
```

```
pcf8574:
  - id: pcf8574_hub
    address: 0x20

binary_sensor:
  - platform: gpio
    pin:
      pcf8574: pcf8574_hub
      number: 0
      mode: INPUT
    name: Pin0
    inverted: False
```
Build fails with and without the `inverted` parameter.

**Comment by apeeters** [comment]
PCF8574 works fine!
