### ISSUE TITLE
Compile error when using raw remote_receiver

### ISSUE THREAD

**Issue by escoand** [OttoWinter/esphomeyaml#164]
Since 1.8 I've problems with raw values for remote_receiver:

```
INFO [esphomeyaml.config] Reading configuration...
INFO [esphomeyaml.__main__] Generating C++ source...
Traceback (most recent call last):
  File "/usr/bin/esphomeyaml", line 11, in <module>
    load_entry_point('esphomeyaml', 'console_scripts', 'esphomeyaml')()
  File "/esphomeyaml/__main__.py", line 488, in main
    return run_esphomeyaml(sys.argv)
  File "/esphomeyaml/__main__.py", line 478, in run_esphomeyaml
    return POST_CONFIG_ACTIONS[args.command](args, config)
  File "/esphomeyaml/__main__.py", line 300, in command_compile
    exit_code = write_cpp(config)
  File "/esphomeyaml/__main__.py", line 134, in write_cpp
    flush_tasks()
  File "/esphomeyaml/helpers.py", line 464, in flush_tasks
    task.next()
  File "/esphomeyaml/helpers.py", line 443, in func_
    for _ in func(*args):
  File "/esphomeyaml/components/binary_sensor/remote_receiver.py", line 108, in to_code
    rhs = receiver_base(config)
  File "/esphomeyaml/components/binary_sensor/remote_receiver.py", line 77, in receiver_base
    data = ArrayInitializer(*config[CONF_RAW], multiline=False)
TypeError: list indices must be integers, not strstr
```

The corresponding configuration is:
```yaml
binary_sensor:
  - platform: remote_receiver
    name: SamsungRemotePower
    raw: [ 4500,-4500,
           560,-1690, 560,-1690, 560,-1690, 560,-560, 560,-560, 560,-560, 560
,-560, 560,-560,
           560,-1690, 560,-1690, 560,-1690, 560,-560, 560,-560, 560,-560, 560
,-560, 560,-560,
           560,-560, 560,-1690, 560,-560, 560,-560, 560,-560, 560,-560, 560,-
560, 560,-560,
           560,-1690, 560,-560, 560,-1690, 560,-1690, 560,-1690, 560,-1690, 5
60,-1690, 560,-1690,
           560,-10000 ]
    filters:
      - delayed_off: 200ms
  - platform: remote_receiver
    id: remote_familystory
    raw: [ 4500,-4500,
           560,-1690, 560,-1690, 560,-1690, 560,-560, 560,-560, 560,-560, 560
,-560, 560,-560,
           560,-1690, 560,-1690, 560,-1690, 560,-560, 560,-560, 560,-560, 560
,-560, 560,-560,
           560,-560, 560,-1690, 560,-1690, 560,-560, 560,-560, 560,-560, 560,
-1690, 560,-1690,
           560,-1690, 560,-560, 560,-560, 560,-1690, 560,-1690, 560,-1690, 56
0,-560, 560,-560,
           560,-10000 ]
    on_click:
      then:
        - mqtt.publish:
            topic: licht_sofa/light/sofa/command
            payload: toggle
    filters:
      - delayed_off: 200ms
```

**Comment by OttoWinter** [comment]
Ah yes, that was a typo when refactoring some code (the new tests will catch that in the future).

See https://github.com/OttoWinter/esphomeyaml/pull/158
