### ISSUE TITLE
esphomeyaml-edge: hass.io addon not starting

### ISSUE THREAD

**Issue by TheJulianJES** [OttoWinter/esphomeyaml#277]
**Operating environment (Hass.io/Docker/pip/etc.):**
Hass.io

**ESP (ESP32/ESP8266/Board/Sonoff):**
ESP8266 (not relevant for this issue though)

**Affected component:**
esphomeyaml Dashboard

**Description of problem:**
Tried rebuilding the latest esphomeyaml-edge and I couldn't login via my hass.io credentials. Then I reinstalled the addon because it also didn't show the updated badges (like auth badge -> maybe the config.json doesn't get "checked again" when rebuilding) in the hassio interface. Now for some reason the network tab is missing (where you configure the port in hassio) and this is the error I see in the logs: https://pastebin.com/raw/SihacNUK

**Problem-relevant YAML-configuration entries:**
(Not relevant) / default hass.io addon config:
```yaml
{
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}
```

**Traceback (if applicable):**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: esphomeyaml-edge vdev

 Development Version! Manage and program ESP8266/ESP32 microcontrollers through YAML configuration files

 From: esphomeyaml Hass.io Add-Ons
 By: Otto Winter <contact@otto-winter.com>
-----------------------------------------------------------
 amd64 / null / HA 0.84.6 / SU 141 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 

[17:12:03+0100] INFO ----> You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 20-nginx.sh: executing... 
[cont-init.d] 20-nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[17:12:03+0100] INFO ----> Starting NGINX...
[services.d] done.
[17:12:03+0100] INFO ----> Starting esphomeyaml dashboard...
INFO Starting dashboard web server on port 80 and configuration dir /config/esphomeyaml...
Traceback (most recent call last):
  File "/usr/local/bin/esphomeyaml", line 11, in <module>
    load_entry_point('esphomeyaml==1.10.0.dev0', 'console_scripts', 'esphomeyaml')()
  File "/usr/local/lib/python2.7/dist-packages/esphomeyaml/__main__.py", line 494, in main
    return run_esphomeyaml(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/esphomeyaml/__main__.py", line 470, in run_esphomeyaml
    return PRE_CONFIG_ACTIONS[args.command](args)
  File "/usr/local/lib/python2.7/dist-packages/esphomeyaml/__main__.py", line 360, in command_dashboard
    return dashboard.start_web_server(args)
  File "/usr/local/lib/python2.7/dist-packages/esphomeyaml/dashboard/dashboard.py", line 554, in start_web_server
    app.listen(args.port)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2042, in listen
    server.listen(port, address)
  File "/usr/local/lib/python2.7/dist-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python2.7/dist-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
[17:12:04+0100] INFO ----> Starting esphomeyaml dashboard...
INFO Starting dashboard web server on port 80 and configuration dir /config/esphomeyaml...
Traceback (most recent call last):
  File "/usr/local/bin/esphomeyaml", line 11, in <module>
    load_entry_point('esphomeyaml==1.10.0.dev0', 'console_scripts', 'esphomeyaml')()
  File "/usr/local/lib/python2.7/dist-packages/esphomeyaml/__main__.py", line 494, in main
    return run_esphomeyaml(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/esphomeyaml/__main__.py", line 470, in run_esphomeyaml
    return PRE_CONFIG_ACTIONS[args.command](args)
  File "/usr/local/lib/python2.7/dist-packages/esphomeyaml/__main__.py", line 360, in command_dashboard
    return dashboard.start_web_server(args)
  File "/usr/local/lib/python2.7/dist-packages/esphomeyaml/dashboard/dashboard.py", line 554, in start_web_server
    app.listen(args.port)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2042, in listen
    server.listen(port, address)
  File "/usr/local/lib/python2.7/dist-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python2.7/dist-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
[17:12:05+0100] INFO ----> Starting esphomeyaml dashboard...
INFO Starting dashboard web server on port 80 and configuration dir /config/esphomeyaml...
Traceback (most recent call last):
  File "/usr/local/bin/esphomeyaml", line 11, in <module>
    load_entry_point('esphomeyaml==1.10.0.dev0', 'console_scripts', 'esphomeyaml')()
  File "/usr/local/lib/python2.7/dist-packages/esphomeyaml/__main__.py", line 494, in main
    return run_esphomeyaml(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/esphomeyaml/__main__.py", line 470, in run_esphomeyaml
    return PRE_CONFIG_ACTIONS[args.command](args)
  File "/usr/local/lib/python2.7/dist-packages/esphomeyaml/__main__.py", line 360, in command_dashboard
    return dashboard.start_web_server(args)
  File "/usr/local/lib/python2.7/dist-packages/esphomeyaml/dashboard/dashboard.py", line 554, in start_web_server
    app.listen(args.port)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2042, in listen
    server.listen(port, address)
  File "/usr/local/lib/python2.7/dist-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python2.7/dist-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
[17:12:06+0100] INFO ----> Starting esphomeyaml dashboard...
```

**Additional information:**
Dashboard shows:
![image](https://user-images.githubusercontent.com/6409465/50494544-278a8280-0a24-11e9-9ea7-fbeb0c3acf49.png)

Previously (with network tab):
<img width="640" alt="bildschirmfoto 2018-12-27 um 22 12 32" src="https://user-images.githubusercontent.com/6409465/50494599-9536ae80-0a24-11e9-8ca3-40f8a34f5fe1.png">

Now (without network tab):
![image](https://user-images.githubusercontent.com/6409465/50494612-a7185180-0a24-11e9-8b93-b39b61c0de96.png)

**Comment by OttoWinter** [comment]
You have another service running on the 6052 port (or the port you configured in the Hass.io addon settings).

It's pretty clear because the page you're seeing there is the apache setup page, but esphomeyaml uses nginx. I bet you you will still see that page when thr add-on is not running.

Closing as configuration issue.

**Comment by OttoWinter** [comment]
As for the missing network tab, it's probably due to a bug in Hass.io - please check yiu're using the latest version of that.

**Comment by TheJulianJES** [comment]
Hey, thanks for the quick response!
I am actually running that page on port 80 (proxy stuff for hass).
But in the screenshot already provided the page is somehow "relayed" to the 6052 port which should display the esphomeyaml dashboard.

(It seems like the dashboard somehow starts on port 80 (which is occupied) and the apache server which is running there somehow gets "relayed" to the port 6052.)

Here you can see that this is not happening when the (edge) addon is shutdown.
![image](https://user-images.githubusercontent.com/6409465/50494708-332a7900-0a25-11e9-8ecf-6ec8ac6081b7.png)

Hass.io supervisor version 141 is currently the latest (which I'm running).
 
I already re-added the repo and reinstalled the addon two times, but I'll try again shortly.

**Comment by TheJulianJES** [comment]
Uninstalled all esphomeyaml addons, removed the repo again.
Added the repo and only installed the esphomeyaml-edge addon and the network tab is still missing.
I'm not sure if this is a hass.io issue or a config.json issue of the esphomeyaml-edge addon.
I'll try to see if I can come up with a solution and will try installing the addon on a clean hass.io setup.

**Comment by TheJulianJES** [comment]
Setting host_network to false (or removing the line) in the esphomeyaml-edge/config.json solved the issue.
(Tested using a fork)
Of course this is "against" the point of hass.io's implementation but it seems like the network tab only shows up, when host_network is disabled (like it is in the current esphomeyaml and esphomeyaml-beta addon)
```"host_network": false,```

When doing this, the addon correctly starts on port 6052 and also shows the correct dashboard.

**Comment by TheJulianJES** [comment]
It seems like this is done intentionally on the hass.io side:
https://github.com/home-assistant/hassio/blob/dev/hassio/addons/addon.py#L261-L264

**Comment by TheJulianJES** [comment]
Updated the issue to (hopefully) make it more clear on what's actually going on.
Sorry, because of the Apache part. It's running on port 80 and was displayed only when the addon was started also on port 6052 (due to the missing network tab -> causing the addon trying to start on port 80).
