### ISSUE TITLE
Failure to run after OTA.

### ISSUE THREAD

**Issue by RaveGun** [OttoWinter/esphomeyaml#327]
**Operating environment (Hass.io/Docker/pip/etc.):**

Python 27 env on Anaconda3 on a Win10 PC.

**ESP (ESP32/ESP8266/Board/Sonoff):**

NodeMCU v2

**Affected component:**

run after an OTA

**Description of problem:**
If I call:
```esphomeyaml flame.yaml run --upload-port 192.168.1.123```

it flashes correctly but after it fails to connect and continue logging:
```INFO Successfully compiled program.
INFO Connecting to 192.168.1.123
INFO Uploading flame\.pioenvs\flame\firmware.bin (367008 bytes)
Uploading: [============================================================] 100% Done...

INFO Waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
Traceback (most recent call last):
  File "f:\devapp\anaconda3\envs\py27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "f:\devapp\anaconda3\envs\py27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "F:\DevApp\Anaconda3\envs\py27\Scripts\esphomeyaml.exe\__main__.py", line 9, in <module>
  File "f:\devapp\anaconda3\envs\py27\lib\site-packages\esphomeyaml\__main__.py", line 503, in main
    return run_esphomeyaml(sys.argv)
  File "f:\devapp\anaconda3\envs\py27\lib\site-packages\esphomeyaml\__main__.py", line 493, in run_esphomeyaml
    return POST_CONFIG_ACTIONS[args.command](args, config)
  File "f:\devapp\anaconda3\envs\py27\lib\site-packages\esphomeyaml\__main__.py", line 316, in command_run
    return show_logs(config, args, port)
  File "f:\devapp\anaconda3\envs\py27\lib\site-packages\esphomeyaml\__main__.py", line 218, in show_logs
    return run_logs(config, port)
  File "f:\devapp\anaconda3\envs\py27\lib\site-packages\esphomeyaml\api\client.py", line 423, in run_logs
    conf = config['api']
KeyError: 'api'
```

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
`esphomeyaml:
  name: flame
  platform: ESP8266
  board: nodemcuv2
  esphomelib_version: dev
  arduino_version: dev
  #use_custom_code: false

wifi:
  ssid: 'Searching...'
  password: 'yetanotherbug'

mqtt:
  broker: '192.168.1.90'
  username: 'homeassistant'
  password: 'yetanotherbug'
  discovery_prefix: 'homeassistant'

# Enable logging
logger:

ota:
  password: 'yetanotherbug'

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO12
    num_leds: 60
    rgb_order: GRB
    name: "Fire"
#    effects:
#      - addressable_random_twinkle:
#      - addressable_random_twinkle:
#          name: Random Twinkle Effect With Custom Values
#          twinkle_probability: 5%
#          progress_interval: 16ms
``

**Traceback (if applicable):**
<!--
Please copy the traceback here if compilation is failing. If possible, also connect to the ESP and copy its logs into the backticks.
-->
```

```

**Additional information:**

**Comment by exxamalte** [comment]
I can confirm that I had the same issue here just now.
It appears that if the firmware update is performed via the network the code assumes that you are using the new api and thus tries to find the key `api` in the configuration.

In my case this issue was obscured because with this version (1.10.0) the ESP couldn't find my wifi network anymore which does not broadcast its SSID. This was working fine up to version 1.9.3.
